# Generated by Django 4.1.4 on 2022-12-17 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_alter_stock_logo_alter_stock_name_alter_stock_sector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='logo',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
